# Generated by Django 4.0.6 on 2022-09-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMascota', models.CharField(max_length=30)),
                ('razaMascota', models.CharField(max_length=50)),
                ('especieMascota', models.CharField(max_length=50)),
                ('fechaNacimientoMascota', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='datosPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePropietario', models.CharField(max_length=30)),
                ('apellidoPropietario', models.CharField(max_length=30)),
                ('fechaNacimientoPropietario', models.DateField()),
                ('dniPropietario', models.IntegerField()),
                ('emailPropietario', models.EmailField(max_length=254)),
                ('direccionPropietario', models.CharField(max_length=200)),
                ('barrioPropietario', models.CharField(max_length=30)),
                ('ciudadPropietario', models.CharField(max_length=50)),
                ('telefonoPropietario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='datosVeterinarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVet', models.CharField(max_length=30)),
                ('apellidoVet', models.CharField(max_length=30)),
                ('fechaNacimientoVet', models.DateField()),
                ('matriculaVet', models.IntegerField()),
                ('emailVet', models.EmailField(max_length=254)),
                ('telefonoVet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='historiaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsulta', models.DateTimeField()),
                ('sexoMascota', models.CharField(max_length=30)),
                ('pesoMascota', models.FloatField(max_length=5)),
                ('colorMascota', models.CharField(max_length=30)),
                ('enfermedadPreviaMascota', models.CharField(max_length=250)),
                ('vacunasMascotas', models.CharField(max_length=100)),
                ('comidaMascota', models.CharField(max_length=100)),
                ('temperaturaMascota', models.FloatField()),
                ('motivoConsulta', models.CharField(max_length=250)),
                ('diagnosticoMascota', models.CharField(max_length=350)),
                ('veterinarioMascota', models.CharField(max_length=50)),
            ],
        ),
    ]
